### ISSUE TITLE
error on starting sidekiq 6.5.5 and sidekiq-scheduler 4.0.2

### ISSUE THREAD

**Issue by tfader** [sidekiq-scheduler/sidekiq-scheduler#406]
Full stack:
2022-09-15T20:22:19.432Z pid=12043 tid=c9j INFO: Scheduling ClearBlockadesJob {"cron"=>"10 * * * * Europe/Warsaw", "class"=>"ClearBlockadesJob"}
2022-09-15T20:22:19.436Z pid=12043 tid=c9j WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
2022-09-15T20:22:19.436Z pid=12043 tid=c9j WARN: TypeError: Unsupported command argument type: EtOrbi::EoTime
2022-09-15T20:22:19.436Z pid=12043 tid=c9j WARN: /Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.8.0/lib/redis_client/command_builder.rb:37:in `block in generate'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.8.0/lib/redis_client/command_builder.rb:28:in `map!'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.8.0/lib/redis_client/command_builder.rb:28:in `generate'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.8.0/lib/redis_client.rb:210:in `call_v'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis/client.rb:80:in `call_v'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis.rb:167:in `block in send_command'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis.rb:166:in `synchronize'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis.rb:166:in `send_command'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis/commands/hashes.rb:26:in `hset'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:201:in `block in hset'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:164:in `block in redis'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:161:in `redis'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:201:in `hset'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:63:in `set_job_next_time'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/utils.rb:127:in `update_job_next_time'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:120:in `block in load_schedule_job'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:111:in `each'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:111:in `load_schedule_job'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:89:in `block in load_schedule!'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:87:in `each'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:87:in `load_schedule!'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/manager.rb:33:in `start'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:24:in `block (2 levels) in <top (required)>'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:57:in `block in fire_event'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:56:in `each'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:56:in `fire_event'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/cli.rb:105:in `run'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/bin/sidekiq:31:in `<top (required)>'
/Users/.............../.rbenv/versions/3.1.2/bin/sidekiq:25:in `load'
/Users/.............../.rbenv/versions/3.1.2/bin/sidekiq:25:in `<top (required)>'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `load'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in `run'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in `exec'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
/Users/.............../.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/Users/.............../.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
2022-09-15T20:22:19.436Z pid=12043 tid=c9j WARN: TypeError: Unsupported command argument type: EtOrbi::EoTime
2022-09-15T20:22:19.436Z pid=12043 tid=c9j WARN: /Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.8.0/lib/redis_client/command_builder.rb:37:in `block in generate'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.8.0/lib/redis_client/command_builder.rb:28:in `map!'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.8.0/lib/redis_client/command_builder.rb:28:in `generate'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.8.0/lib/redis_client.rb:210:in `call_v'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis/client.rb:80:in `call_v'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis.rb:167:in `block in send_command'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis.rb:166:in `synchronize'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis.rb:166:in `send_command'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.4/lib/redis/commands/hashes.rb:26:in `hset'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:201:in `block in hset'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:164:in `block in redis'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:161:in `redis'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:201:in `hset'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:63:in `set_job_next_time'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/utils.rb:127:in `update_job_next_time'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:120:in `block in load_schedule_job'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:111:in `each'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:111:in `load_schedule_job'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:89:in `block in load_schedule!'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:87:in `each'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:87:in `load_schedule!'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/manager.rb:33:in `start'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:24:in `block (2 levels) in <top (required)>'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:57:in `block in fire_event'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:56:in `each'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:56:in `fire_event'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/cli.rb:105:in `run'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/bin/sidekiq:31:in `<top (required)>'
/Users/.............../.rbenv/versions/3.1.2/bin/sidekiq:25:in `load'
/Users/.............../.rbenv/versions/3.1.2/bin/sidekiq:25:in `<top (required)>'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `load'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in `run'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in `exec'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/.............../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
/Users/.............../.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/Users/.............../.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'

**Comment by tfader** [comment]
works with sidekiq 6.5.6
