### ISSUE TITLE
Did sidekiq-scheduler 5.0.0 add a Rails dependency?

### ISSUE THREAD

**Issue by mphilips-copper** [sidekiq-scheduler/sidekiq-scheduler#424]
Hi,

I'm using sidekiq-scheduler in my Sinatra app, when I use 5.0.0 I am not able to start it up:

```
2023-01-27T22:12:44.090Z pid=1 tid=zl INFO: Running in ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
2023-01-27T22:12:44.092Z pid=1 tid=zl INFO: See LICENSE and the LGPL-3.0 for licensing details.
2023-01-27T22:12:44.094Z pid=1 tid=zl INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2023-01-27T22:12:44.094Z pid=1 tid=zl INFO: Sidekiq 7.0.3 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://cache:6379"}
2023-01-27T22:12:44.101Z pid=1 tid=zl INFO: Sidekiq 7.0.3 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>"redis://cache:6379"}
2023-01-27T22:12:44.103Z pid=1 tid=zl WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup","_config":"#<Sidekiq::Config:0x00007f7db8a3c568>"}
2023-01-27T22:12:44.106Z pid=1 tid=zl WARN: NoMethodError: undefined method `present?' for nil:NilClass

      config.schedule = Sidekiq.schedule if Sidekiq.schedule.present?
                                                            ^^^^^^^^^
2023-01-27T22:12:44.109Z pid=1 tid=zl WARN: /usr/local/bundle/gems/sidekiq-scheduler-5.0.0/lib/sidekiq-scheduler/manager.rb:38:in `set_current_scheduler_options'
/usr/local/bundle/gems/sidekiq-scheduler-5.0.0/lib/sidekiq-scheduler/manager.rb:12:in `initialize'
/usr/local/bundle/gems/sidekiq-scheduler-5.0.0/lib/sidekiq-scheduler.rb:20:in `new'
/usr/local/bundle/gems/sidekiq-scheduler-5.0.0/lib/sidekiq-scheduler.rb:20:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:58:in `block in fire_event'
/usr/local/bundle/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:57:in `each'
/usr/local/bundle/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:57:in `fire_event'
/usr/local/bundle/gems/sidekiq-7.0.3/lib/sidekiq/cli.rb:106:in `run'
/usr/local/bundle/gems/sidekiq-7.0.3/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<main>'
undefined method `present?' for nil:NilClass

      config.schedule = Sidekiq.schedule if Sidekiq.schedule.present?
                                                            ^^^^^^^^^
/usr/local/bundle/gems/sidekiq-scheduler-5.0.0/lib/sidekiq-scheduler/manager.rb:38:in `set_current_scheduler_options'
/usr/local/bundle/gems/sidekiq-scheduler-5.0.0/lib/sidekiq-scheduler/manager.rb:12:in `initialize'
/usr/local/bundle/gems/sidekiq-scheduler-5.0.0/lib/sidekiq-scheduler.rb:20:in `new'
/usr/local/bundle/gems/sidekiq-scheduler-5.0.0/lib/sidekiq-scheduler.rb:20:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:58:in `block in fire_event'
/usr/local/bundle/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:57:in `each'
/usr/local/bundle/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:57:in `fire_event'
/usr/local/bundle/gems/sidekiq-7.0.3/lib/sidekiq/cli.rb:106:in `run'
/usr/local/bundle/gems/sidekiq-7.0.3/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<main>'
exit code: 1
```

I'm wondering if the call to `.present?` was added unintentionally? If I revert to [sidekiq-scheduler 4.0.3](https://github.com/sidekiq-scheduler/sidekiq-scheduler/blob/v4.0.3/lib/sidekiq-scheduler/manager.rb#L38), which does not seem to make the same call, it starts up fine:

```
2023-01-27T22:54:34.412Z pid=1 tid=17d INFO: Running in ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
2023-01-27T22:54:34.415Z pid=1 tid=17d INFO: See LICENSE and the LGPL-3.0 for licensing details.
2023-01-27T22:54:34.415Z pid=1 tid=17d INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2023-01-27T22:54:34.416Z pid=1 tid=17d INFO: Booting Sidekiq 6.5.5 with Sidekiq::RedisConnection::RedisAdapter options {:url=>"redis://cache:6379"}
2023-01-27T22:54:34.422Z pid=1 tid=17d INFO: Loading Schedule
2023-01-27T22:54:34.423Z pid=1 tid=17d INFO: Schedule empty! Set Sidekiq.schedule
2023-01-27T22:54:34.424Z pid=1 tid=17d INFO: Schedules Loaded
```

Thanks!

**Comment by marcelolx** [comment]
yeah that is possible, we did switch from a `nil?` check to a `present?`... Will fix it and make a release when I have some time

**Comment by mphilips-copper** [comment]
it's working for me now with 5.0.1, thanks again for the assistance!

```
2023-01-28T14:34:56.589Z pid=1 tid=zl INFO: Running in ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
2023-01-28T14:34:56.593Z pid=1 tid=zl INFO: See LICENSE and the LGPL-3.0 for licensing details.
2023-01-28T14:34:56.593Z pid=1 tid=zl INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2023-01-28T14:34:56.593Z pid=1 tid=zl INFO: Sidekiq 7.0.3 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://cache:6379"}
2023-01-28T14:34:56.601Z pid=1 tid=zl INFO: Sidekiq 7.0.3 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>"redis://cache:6379"}
2023-01-28T14:34:56.605Z pid=1 tid=zl INFO: Loading Schedule
2023-01-28T14:34:56.607Z pid=1 tid=zl INFO: Scheduling hello_world {"every"=>"5s", "class"=>"HelloWorld", "queue"=>"default"}
2023-01-28T14:34:56.610Z pid=1 tid=zl INFO: Schedules Loaded
2023-01-28T14:35:01.789Z pid=1 tid=15p INFO: queueing HelloWorld (hello_world)
...
```
