### ISSUE TITLE
Error handler threw an error

### ISSUE THREAD

**Issue by route** [sidekiq-scheduler/sidekiq-scheduler#453]
sidekiq (7.1.4)
sidekiq-scheduler (5.0.3)

Whenever an error occurs in the worker sidekiq cannot dump context to the output because of `sidekiq-scheduler` resulting in:

```
2023-09-19T07:14:02.220Z pid=34019 tid=4jv7 class=Worker jid=17815f7c6eb961071a9c4d1d elapsed=0.448 INFO: fail
2023-09-19T07:14:02.222Z pid=34019 tid=4jv7 ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
2023-09-19T07:14:02.222Z pid=34019 tid=4jv7 ERROR: stack level too deep
2023-09-19T07:14:02.223Z pid=34019 tid=4jv7 ERROR: /Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/instance_variables.rb:15:in `map'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/instance_variables.rb:15:in `instance_values'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:63:in `as_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:180:in `block in as_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:179:in `each'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:179:in `as_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:63:in `as_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:180:in `block in as_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:179:in `each'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:179:in `as_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:63:in `as_json'

... and so on

/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:180:in `block in as_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:179:in `each'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:63:in `as_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/json/encoding.rb:35:in `encode'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/json/encoding.rb:22:in `encode'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/object/json.rb:42:in `to_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq.rb:57:in `generate'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq.rb:57:in `dump_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:60:in `to_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq.rb:57:in `generate'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq.rb:57:in `dump_json'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:40:in `block in <class:Config>'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:269:in `block in handle_exception'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:268:in `each'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:268:in `handle_exception'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:48:in `handle_exception'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:48:in `handle_exception'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:190:in `rescue in process'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:181:in `process'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:82:in `process_one'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:72:in `run'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:10:in `watchdog'
/Users/route/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:19:in `block in safe_thread'
```

**Comment by route** [comment]
Looks like it's a combination of gems above + gem 'oj', '3.10.6' with `Oj::Rails.mimic_JSON`
